[package]
name = "rsproto"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
once_cell = "1.19.0"
tempfile = "3.12.0"

[dev-dependencies]
sha2 = "0.10.8"

[profile.release]
codegen-units = 1
lto = false
